import { z } from 'zod';

export const devoteeSchema = z.object({
    name: z.string().min(1, 'Full name is required'),
    spiritualName: z.string().optional(),
    email: z.string().email('Invalid email address').optional().or(z.literal('')),
    gender: z.enum(['Male', 'Female', 'Other']),
    dob: z.string().optional(),
    age: z.string().optional(),
    bloodGroup: z.string().optional(),
    education: z.string().optional(),
    occupation: z.string().optional(),
    relationType: z.enum(['Father', 'Husband', 'Wife']),
    guardianName: z.string().optional(),
    contact: z.string()
        .min(1, 'Contact number is required')
        .regex(/^[6-9]\d{9}$/, 'Enter a valid 10-digit mobile number'),
    whatsapp: z.string().optional(),
    address: z.string().optional(),
    village: z.string().optional(),
    district: z.string().optional(),
    pinCode: z.string().optional(),
    state: z.string().optional(),
    maritalStatus: z.enum(['Single', 'Married', 'Divorced', 'Widowed']),
    skills: z.string().optional(),
    specialDay: z.string().optional(),
    specialDayName: z.string().optional(),
    spiritualStatus: z.enum(['Aspiring', 'Sheltered', 'Initiated']),
    initiatedName: z.string().optional(),
    counselor: z.string().optional(),
    spiritualMaster: z.string().optional(),
    shelterDate: z.string().optional(),
    initiatedDate1: z.string().optional(),
    initiatedDate2: z.string().optional(),
    rounds: z.string().optional(),
    followingPrinciplesSince: z.string().optional(),
    booksRead: z.array(z.string()).optional(),
    booksReading: z.string().optional(),
    courses: z.array(z.string()).optional(),
    anniversary: z.string().optional(),
    shraddhaName: z.string().optional(),
    shraddhaDate: z.string().optional(),
    feedback: z.string().optional(),
    child1Name: z.string().optional(),
    child1Dob: z.string().optional(),
    child1Status: z.string().optional(),
    child2Name: z.string().optional(),
    child2Dob: z.string().optional(),
    child2Status: z.string().optional(),
    child3Name: z.string().optional(),
    child3Dob: z.string().optional(),
    child3Status: z.string().optional(),
    otherFamilyMembers: z.string().optional(),
    currentService: z.string().optional(),
    photo: z.string().optional(),
});
